package Programa;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fran
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
        this.setSize(890,435);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTF6 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jTF5 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jTF2 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTF6.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        jTF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 220, 30));

        l6.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        l6.setText("CLAVE DE TARJETA");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 30));

        l5.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        l5.setText("MONTO AUTORIZADO");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jTF5.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        getContentPane().add(jTF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 140, 30));

        l4.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        l4.setText("FECHA DE INGRESO");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 30));

        jTF4.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        getContentPane().add(jTF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 140, 30));

        l3.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        l3.setText("INGRESOS MENSUALES");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jTF3.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        getContentPane().add(jTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 650, 30));

        jTF2.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        jTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 260, 30));

        l2.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        l2.setText("NOMBRE");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));

        l1.setFont(new java.awt.Font("Caviar Dreams", 1, 18)); // NOI18N
        l1.setText("CLAVE CLIENTE");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        jTF1.setFont(new java.awt.Font("Caviar Dreams", 0, 18)); // NOI18N
        getContentPane().add(jTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 140, 30));

        jButton5.setText("CONSULTAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, 30));

        jButton4.setText("MODIFICAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, 30));

        jButton3.setText("INGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, 30));

        jButton1.setText("BUSCAR CLIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 150, 30));

        jButton2.setText("CLAVE A MODIFICAR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, 30));

        jScrollPane1.setFont(new java.awt.Font("Caviar Dreams", 0, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 830, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF6ActionPerformed

    private void jTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
    Connection con;
    con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=EJEM25; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec CON1");
    tabla.addColumn("CLAVE DE CLIENTE");
    tabla.addColumn("NOMBRE");
    tabla.addColumn("FECHA DE INGRESO");
    tabla.addColumn("INGRESO");
    tabla.addColumn("MONTO");
    tabla.addColumn("TIPO DE TARJETA");
    
    while (rs.next())
    {
        Object dato[]=new Object[6];
        for (int i=0;i<6;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) {}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try{
                    
                    String clave_c, nom_c, fecha, ing, monto, c_t;
                     
                    clave_c=jTF1.getText();
                    nom_c=jTF3.getText();
                    fecha=jTF2.getText();
                    ing=jTF4.getText();
                    monto=jTF5.getText();
                    c_t=jTF6.getText();
                                       
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=EJEM25;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                   
                    ResultSet rs=stmt.executeQuery("exec INGCLIENTE "+clave_c+",'"+nom_c+"','"+fecha+"',"+ing+","+monto+","+c_t+"");
                    
                }
                catch(SQLException e)  {
                    
                } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try
    {
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=EJEM25; user=SA; password=SASA;");
    //Connection con=DriverManager.getConnection("jdbc:odbc:prueba");
    Statement stmt=con.createStatement();
   ResultSet rs=stmt.executeQuery("exec BUS "+jTF1.getText()+"");
  
    tabla.addColumn("CLAVE DE CLIENTE");
    tabla.addColumn("NOMBRE");
    tabla.addColumn("FECHA DE INGRESO");
    tabla.addColumn("INGRESO");
    tabla.addColumn("MONTO");
    tabla.addColumn("TIPO DE TARJETA");
       
    while (rs.next())
    {
        Object dato[]=new Object[6];
        for (int i=0;i<6;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(SQLException e) {}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    public javax.swing.JTextField jTF6;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    // End of variables declaration//GEN-END:variables
}
