package Programa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home1
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form bc
     */
    public Consulta() {
        initComponents();
    }
    String a;
    int y,x;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bRegresar = new javax.swing.JButton();
        bMinimizar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        lBarra = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDelegacion = new javax.swing.JLabel();
        jColonia = new javax.swing.JLabel();
        jCalle = new javax.swing.JLabel();
        jAyudante = new javax.swing.JLabel();
        jEmpresa = new javax.swing.JLabel();
        jInventor = new javax.swing.JLabel();
        jTel = new javax.swing.JLabel();
        jPatente = new javax.swing.JLabel();
        jEmpresa1 = new javax.swing.JLabel();
        jEmpresa3 = new javax.swing.JLabel();
        jEmpresa4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(44, 109, 212));
        jPanel3.setForeground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bRegresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bRegresar.setForeground(new java.awt.Color(255, 255, 255));
        bRegresar.setText("<");
        bRegresar.setBorder(null);
        bRegresar.setBorderPainted(false);
        bRegresar.setContentAreaFilled(false);
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });
        jPanel3.add(bRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        bMinimizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        bMinimizar.setText("-");
        bMinimizar.setBorder(null);
        bMinimizar.setBorderPainted(false);
        bMinimizar.setContentAreaFilled(false);
        bMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinimizarActionPerformed(evt);
            }
        });
        jPanel3.add(bMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 20, 20));

        bSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("x");
        bSalir.setBorder(null);
        bSalir.setBorderPainted(false);
        bSalir.setContentAreaFilled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel3.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, 20));

        lBarra.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        lBarra.setForeground(new java.awt.Color(240, 240, 240));
        lBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBarra.setText("Consulta");
        lBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lBarraMouseDragged(evt);
            }
        });
        lBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lBarraMousePressed(evt);
            }
        });
        jPanel3.add(lBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 40));

        jPanel1.setBackground(new java.awt.Color(49, 126, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© Prototype by Isolated Systems");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PrototypeX");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVergas2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 100));

        jDelegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/condelegacion.png"))); // NOI18N
        jDelegacion.setToolTipText("Consultar delegación.");
        jDelegacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDelegacionMouseClicked(evt);
            }
        });
        jPanel1.add(jDelegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 50, 50));

        jColonia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/concolonia.png"))); // NOI18N
        jColonia.setToolTipText("Consultar colonia.");
        jColonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jColoniaMouseClicked(evt);
            }
        });
        jPanel1.add(jColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 50, 50));

        jCalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/concalle.png"))); // NOI18N
        jCalle.setToolTipText("Consultar calle.");
        jCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalleMouseClicked(evt);
            }
        });
        jPanel1.add(jCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 50, 50));

        jAyudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conayudante.png"))); // NOI18N
        jAyudante.setToolTipText("Consultar ayudante");
        jAyudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAyudanteMouseClicked(evt);
            }
        });
        jPanel1.add(jAyudante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 50, 50));

        jEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conempresa.png"))); // NOI18N
        jEmpresa.setToolTipText("Consultar empresas.");
        jEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresaMouseClicked(evt);
            }
        });
        jPanel1.add(jEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 50, 50));

        jInventor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/coninventor.png"))); // NOI18N
        jInventor.setToolTipText("Consultar inventor");
        jInventor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInventorMouseClicked(evt);
            }
        });
        jPanel1.add(jInventor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 50, 50));

        jTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/contel.png"))); // NOI18N
        jTel.setToolTipText("Consultar Tipo de Telefono");
        jTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTelMouseClicked(evt);
            }
        });
        jPanel1.add(jTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 50, 50));

        jPatente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conpatente.png"))); // NOI18N
        jPatente.setToolTipText("Consultar patente.");
        jPatente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatenteMouseClicked(evt);
            }
        });
        jPanel1.add(jPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 50, 50));

        jEmpresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/contelemp.png"))); // NOI18N
        jEmpresa1.setToolTipText("Consultar telefono empresas.");
        jEmpresa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresa1MouseClicked(evt);
            }
        });
        jPanel1.add(jEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 50, 50));

        jEmpresa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/contelayu.png"))); // NOI18N
        jEmpresa3.setToolTipText("Consultar telefono ayudante.");
        jEmpresa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresa3MouseClicked(evt);
            }
        });
        jPanel1.add(jEmpresa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 50, 50));

        jEmpresa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/contelinv.png"))); // NOI18N
        jEmpresa4.setToolTipText("Consultar telefono inventor.");
        jEmpresa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresa4MouseClicked(evt);
            }
        });
        jPanel1.add(jEmpresa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 880, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 800, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 880, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_bMinimizarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        this.dispose();
        Menú Men=new Menú();
        Men.setVisible(true);
    }//GEN-LAST:event_bRegresarActionPerformed

    private void jDelegacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDelegacionMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec DEL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("DELEGACIÓN");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jDelegacionMouseClicked

    private void jAyudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAyudanteMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec ayu_1");
    tabla.addColumn("CLAVE");
    tabla.addColumn("AYUDANTE");
    tabla.addColumn("RFC");
    tabla.addColumn("FECHA");
    tabla.addColumn("DELEGACIÓN");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("INVENTOR");
    while (rs.next())
    {
        Object dato[]=new Object[9];
        for (int i=0;i<9;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jAyudanteMouseClicked

    private void jEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresaMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec EMP_1");
    tabla.addColumn("CLAVE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("DELEGACION");
    
    while (rs.next())
    {
        Object dato[]=new Object[5];
        for (int i=0;i<5;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jEmpresaMouseClicked

    private void jColoniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColoniaMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec col");
    tabla.addColumn("CLAVE");
    tabla.addColumn("COLONIA");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jColoniaMouseClicked

    private void jCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalleMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec CAL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("CALLE");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jCalleMouseClicked

    private void jInventorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInventorMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec INV_1");
    tabla.addColumn("CLAVE");
    tabla.addColumn("INVENTOR");
    tabla.addColumn("RFC");
    tabla.addColumn("FECHA");
    tabla.addColumn("DELEGACIÓN");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("ASESOR");
    while (rs.next())
    {
        Object dato[]=new Object[9];
        for (int i=0;i<9;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jInventorMouseClicked

    private void jTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTelMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec TEL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("TIPO DE TELEFONO");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jTelMouseClicked

    private void jPatenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatenteMouseClicked
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec PaT_1");
    tabla.addColumn("CLAVE");
    tabla.addColumn("PATENTE");
    tabla.addColumn("FECHA");
    tabla.addColumn("INVENTOR");
    tabla.addColumn("EMPRESA");
    
    while (rs.next())
    {
        Object dato[]=new Object[5];
        for (int i=0;i<5;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable1.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jPatenteMouseClicked

    private void jEmpresa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresa1MouseClicked
        // TODO add your handling code here:
        try
        {

            DefaultTableModel tabla=new DefaultTableModel();
            Connection con;
            con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("exec TELE_3");
            tabla.addColumn("EMPRESA");
            tabla.addColumn("TIPO");
            tabla.addColumn("NUMERO");
            while (rs.next())
            {
                Object dato[]=new Object[3];
                for (int i=0;i<3;i++)
                {
                    dato[i]=rs.getString(i+1);
                }
                tabla.addRow(dato);
            }
            this.jTable1.setModel(tabla);
        }
        catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jEmpresa1MouseClicked

    private void jEmpresa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresa3MouseClicked
        // TODO add your handling code here:
        try
        {

            DefaultTableModel tabla=new DefaultTableModel();
            Connection con;
            con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("exec TELE_2");
            tabla.addColumn("AYUDANTE");
            tabla.addColumn("TIPO");
            tabla.addColumn("NUMERO");
            while (rs.next())
            {
                Object dato[]=new Object[3];
                for (int i=0;i<3;i++)
                {
                    dato[i]=rs.getString(i+1);
                }
                tabla.addRow(dato);
            }
            this.jTable1.setModel(tabla);
        }
        catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jEmpresa3MouseClicked

    private void jEmpresa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresa4MouseClicked
        // TODO add your handling code here:
        try
        {

            DefaultTableModel tabla=new DefaultTableModel();
            Connection con;
            con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("exec TELE_1");
            tabla.addColumn("INVENTOR");
            tabla.addColumn("TIPO");
            tabla.addColumn("NUMERO");
            while (rs.next())
            {
                Object dato[]=new Object[3];
                for (int i=0;i<3;i++)
                {
                    dato[i]=rs.getString(i+1);
                }
                tabla.addRow(dato);
            }
            this.jTable1.setModel(tabla);
        }
        catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jEmpresa4MouseClicked

    private void lBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lBarraMouseDragged

    private void lBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lBarraMousePressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     
         
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMinimizar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jAyudante;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jColonia;
    private javax.swing.JLabel jDelegacion;
    private javax.swing.JLabel jEmpresa;
    private javax.swing.JLabel jEmpresa1;
    private javax.swing.JLabel jEmpresa3;
    private javax.swing.JLabel jEmpresa4;
    private javax.swing.JLabel jInventor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPatente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTel;
    private javax.swing.JLabel lBarra;
    // End of variables declaration//GEN-END:variables
}
