package IngresarActualizarEliminar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class IAE_Ayudante extends javax.swing.JFrame {

    /**
     * Creates new form I_Ayudante
     */
    public IAE_Ayudante() {
        initComponents();
    }
    int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra = new javax.swing.JPanel();
        bMinimizar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        lBarra = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        jTextField19 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jEliminar = new javax.swing.JButton();
        jActualizarClave = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jIngresar = new javax.swing.JButton();
        jTextField20 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jAyudante = new javax.swing.JLabel();
        jInventor = new javax.swing.JLabel();
        jEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCalle = new javax.swing.JLabel();
        jColonia = new javax.swing.JLabel();
        jDelegacion = new javax.swing.JLabel();
        Tabla = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra.setBackground(new java.awt.Color(44, 109, 212));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMinimizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        bMinimizar.setText("-");
        bMinimizar.setBorder(null);
        bMinimizar.setBorderPainted(false);
        bMinimizar.setContentAreaFilled(false);
        bMinimizar.setRolloverEnabled(false);
        bMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinimizarActionPerformed(evt);
            }
        });
        Barra.add(bMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 20, 20));

        bSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("x");
        bSalir.setBorder(null);
        bSalir.setBorderPainted(false);
        bSalir.setContentAreaFilled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        Barra.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 20, 20));

        bRegresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bRegresar.setForeground(new java.awt.Color(255, 255, 255));
        bRegresar.setText("<");
        bRegresar.setBorder(null);
        bRegresar.setBorderPainted(false);
        bRegresar.setContentAreaFilled(false);
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });
        Barra.add(bRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        lBarra.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        lBarra.setForeground(new java.awt.Color(240, 240, 240));
        lBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBarra.setText("Ayudante");
        lBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lBarraMouseDragged(evt);
            }
        });
        lBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lBarraMousePressed(evt);
            }
        });
        Barra.add(lBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        Contenido.setBackground(new java.awt.Color(49, 126, 247));
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Contenido.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 190, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Fecha:");
        Contenido.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 60, 30));

        jEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/borrar.png"))); // NOI18N
        jEliminar.setToolTipText("Borrar elemento.");
        jEliminar.setContentAreaFilled(false);
        jEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEliminarMouseClicked(evt);
            }
        });
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        Contenido.add(jEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 50, 50));

        jActualizarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/actualizarclave.png"))); // NOI18N
        jActualizarClave.setToolTipText("Actualizar elemento.");
        jActualizarClave.setContentAreaFilled(false);
        jActualizarClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarClaveMouseClicked(evt);
            }
        });
        jActualizarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarClaveActionPerformed(evt);
            }
        });
        Contenido.add(jActualizarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 50, 50));

        jActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/actualizar.png"))); // NOI18N
        jActualizar.setToolTipText("Seleccionar elemento a actualizar.");
        jActualizar.setContentAreaFilled(false);
        jActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarMouseClicked(evt);
            }
        });
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });
        Contenido.add(jActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 50, 50));

        jIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/ingresar.png"))); // NOI18N
        jIngresar.setToolTipText("Ingresar elemento.");
        jIngresar.setContentAreaFilled(false);
        jIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIngresarMouseClicked(evt);
            }
        });
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        Contenido.add(jIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 50, 50));
        Contenido.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 50, 30));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Clave de inventor:");
        Contenido.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 160, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Clave de empresa:");
        Contenido.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 160, 30));
        Contenido.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 50, 30));
        Contenido.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 50, 30));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Clave de calle:");
        Contenido.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 130, 30));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Clave de colonia:");
        Contenido.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, 30));
        Contenido.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 50, 30));
        Contenido.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 50, 30));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Clave de delegación:");
        Contenido.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 30));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Datos de la dirección:");
        Contenido.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));
        Contenido.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 10));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Clave del ayudante:");
        Contenido.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 170, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Datos del ayudante:");
        Contenido.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 20));
        Contenido.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 50, 30));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Nombre:");
        Contenido.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, 30));
        Contenido.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 540, 30));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("RFC:");
        Contenido.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 50, 30));
        Contenido.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 200, 30));

        jAyudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conayudante.png"))); // NOI18N
        jAyudante.setText("Consultar ayudante.");
        jAyudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAyudanteMouseClicked(evt);
            }
        });
        Contenido.add(jAyudante, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 50, 50));

        jInventor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/coninventor.png"))); // NOI18N
        jInventor.setToolTipText("Consultar inventor");
        jInventor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInventorMouseClicked(evt);
            }
        });
        Contenido.add(jInventor, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 50, 50));

        jEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conempresa.png"))); // NOI18N
        jEmpresa.setToolTipText("Consultar empresas.");
        jEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresaMouseClicked(evt);
            }
        });
        Contenido.add(jEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVergas2.png"))); // NOI18N
        Contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 110));

        jCalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/concalle.png"))); // NOI18N
        jCalle.setToolTipText("Consultar calle.");
        jCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalleMouseClicked(evt);
            }
        });
        Contenido.add(jCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 50, 50));

        jColonia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/concolonia.png"))); // NOI18N
        jColonia.setToolTipText("Consultar colonia.");
        jColonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jColoniaMouseClicked(evt);
            }
        });
        Contenido.add(jColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 50, 50));

        jDelegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/condelegacion.png"))); // NOI18N
        jDelegacion.setToolTipText("Consultar delegación.");
        jDelegacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDelegacionMouseClicked(evt);
            }
        });
        Contenido.add(jDelegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 50, 50));

        getContentPane().add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 910, 370));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Clave del inventor", "Nombre del inventor", "Clav. Deleg", "Clav. Col.", "Clav. Calle", "Clav. asesorado"
            }
        ));
        jTable4.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane4.setViewportView(jTable4);

        Tabla.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 830, 130));

        getContentPane().add(Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 910, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_bMinimizarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        new IAE_Menú().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarActionPerformed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraMouseDragged

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraMousePressed

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIngresarActionPerformed

    private void lBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lBarraMouseDragged

    private void lBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lBarraMousePressed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jActualizarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarClaveActionPerformed

    private void jAyudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAyudanteMouseClicked
        // TODO add your handling code here:
        {                                       
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec ayu");
    tabla.addColumn("CLAVE");
    tabla.addColumn("AYUDANTE");
    tabla.addColumn("RFC");
    tabla.addColumn("FECHA");
    tabla.addColumn("DELEGACIÓN");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("INVENTOR");
    while (rs.next())
    {
        Object dato[]=new Object[9];
        for (int i=0;i<9;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }
    }//GEN-LAST:event_jAyudanteMouseClicked

    private void jDelegacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDelegacionMouseClicked
        // TODO add your handling code here:
        {                                         
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec DEL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("DELEGACIÓN");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }
    }//GEN-LAST:event_jDelegacionMouseClicked

    private void jEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresaMouseClicked
 {                                      
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec EMP");
    tabla.addColumn("CLAVE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("DELEGACION");
    
    while (rs.next())
    {
        Object dato[]=new Object[5];
        for (int i=0;i<5;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jEmpresaMouseClicked

    private void jColoniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColoniaMouseClicked
 {                                      
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec col");
    tabla.addColumn("CLAVE");
    tabla.addColumn("COLONIA");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { JOptionPane.showMessageDialog(null,e);}
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jColoniaMouseClicked

    private void jCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalleMouseClicked
 {                                    
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec CAL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("CALLE");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { //JOptionPane.showMessageDialog(null,e)
        }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jCalleMouseClicked

    private void jInventorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInventorMouseClicked
 {                                       
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec INV");
    tabla.addColumn("CLAVE");
    tabla.addColumn("INVENTOR");
    tabla.addColumn("RFC");
    tabla.addColumn("FECHA");
    tabla.addColumn("DELEGACIÓN");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("ASESOR");
    while (rs.next())
    {
        Object dato[]=new Object[9];
        for (int i=0;i<9;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jInventorMouseClicked

    private void jIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIngresarMouseClicked
try{
                    
                    String clave_i, nom_i,rfc, fecha, col, cal, del, emp, ases;
                     
                    clave_i=jTextField25.getText();
                    nom_i=jTextField26.getText();
                    rfc=jTextField27.getText();
                    fecha=jTextField19.getText();
                    col=jTextField23.getText();
                    cal=jTextField22.getText();
                    del=jTextField24.getText();
                    emp=jTextField21.getText();
                    ases=jTextField20.getText();
                    clave_i=clave_i.toUpperCase();
                    nom_i=nom_i.toUpperCase();
                    rfc=rfc.toUpperCase();
                    fecha=fecha.toUpperCase();
                    col=col.toUpperCase();
                    cal=cal.toUpperCase();
                    del=del.toUpperCase();
                    emp=emp.toUpperCase();
                    ases=ases.toUpperCase();
                                       
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                    ResultSet rs=stmt.executeQuery("exec i_ayud '"+clave_i+"','"+nom_i+"',"+rfc+",'"+fecha+"','"+col+"','"+cal+"','"+del+"','"+emp+"','"+ases+"'");
                    
                }
                catch(SQLException e)  {
                    
                } jTextField25.setEnabled(true);  jTextField25.setText("");jTextField26.setText("");jTextField27.setText("");jTextField19.setText("");jTextField23.setText("");
                jTextField22.setText("");jTextField24.setText("");jTextField21.setText("");jTextField20.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_jIngresarMouseClicked

    private void jActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarMouseClicked
 try{      
            String clave_c;
             clave_c = jTextField25.getText();
                
         
                  Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                 ResultSet rs=stmt.executeQuery("select *from AYUDANTE where clave_AYU='"+clave_c+"'");
                if (rs.next()) {
                    jTextField25.setText(String.valueOf(rs.getString(1)));
                    jTextField27.setText(String.valueOf(rs.getString(3)));
                    jTextField26.setText(String.valueOf(rs.getString(2)));
                    jTextField19.setText(String.valueOf(rs.getString(4)));
                    jTextField24.setText(String.valueOf(rs.getString(5)));
                    jTextField23.setText(String.valueOf(rs.getString(6)));
                    jTextField22.setText(String.valueOf(rs.getString(7)));
                    jTextField21.setText(String.valueOf(rs.getString(8)));
                    jTextField20.setText(String.valueOf(rs.getString(9)));
                                         
                    jTextField25.setEnabled(false);
                    
                     
                    stmt.close();
                    
                } 
            } 
        catch (SQLException e) {
         //   JOptionPane.showMessageDialog(null, e);
                
            }       // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarMouseClicked

    private void jActualizarClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarClaveMouseClicked
        // TODO add your handling code here:try{
                    try{
                    String clave_i, nom_i,rfc, fecha, col, cal, del, emp, ases;
                     
                    clave_i=jTextField25.getText();
                    nom_i=jTextField26.getText();
                    rfc=jTextField27.getText();
                    fecha=jTextField19.getText();
                    col=jTextField23.getText();
                    cal=jTextField22.getText();
                    del=jTextField24.getText();
                    emp=jTextField21.getText();
                    ases=jTextField20.getText();
                    clave_i=clave_i.toUpperCase();
                    nom_i=nom_i.toUpperCase();
                    rfc=rfc.toUpperCase();
                    fecha=fecha.toUpperCase();
                    col=col.toUpperCase();
                    cal=cal.toUpperCase();
                    del=del.toUpperCase();
                    emp=emp.toUpperCase();
                    ases=ases.toUpperCase();                   
                    
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                    ResultSet rs=stmt.executeQuery("exec act8 '"+clave_i+"','"+nom_i+"','"+rfc+"','"+fecha+"','"+col+"','"+cal+"','"+del+"','"+emp+"','"+ases+"'");
                    
                }
                catch(SQLException e)  {
                    
                }   jTextField25.setEnabled(true); jTextField25.setText("");jTextField26.setText("");jTextField27.setText("");jTextField19.setText("");jTextField23.setText("");
                jTextField22.setText("");jTextField24.setText("");jTextField21.setText("");jTextField20.setText("");
    }//GEN-LAST:event_jActualizarClaveMouseClicked

    private void jEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEliminarMouseClicked
  try{      
            String clave_t;
             clave_t = jTextField25.getText();
                
         
                  Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                 ResultSet rs=stmt.executeQuery("exec bor8 "+clave_t+"");
        }
        catch(Exception e) {// JOptionPane.showMessageDialog(null, e);
        } jTextField25.setText("");       // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_jEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IAE_Ayudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IAE_Ayudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IAE_Ayudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IAE_Ayudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IAE_Ayudante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Tabla;
    private javax.swing.JButton bMinimizar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jActualizarClave;
    private javax.swing.JLabel jAyudante;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jColonia;
    private javax.swing.JLabel jDelegacion;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jEmpresa;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jInventor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JLabel lBarra;
    // End of variables declaration//GEN-END:variables
}
