/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IngresarActualizarEliminar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class IAE_Inventor extends javax.swing.JFrame {

    /**
     * Creates new form I_Inventor
     */
    public IAE_Inventor() {
        initComponents();
    }
    int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        bMinimizar1 = new javax.swing.JButton();
        bSalir1 = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        lBarra = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jDelegacion = new javax.swing.JLabel();
        jColonia = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jCalle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jInventor = new javax.swing.JLabel();
        jEmpresa = new javax.swing.JLabel();
        jEliminar = new javax.swing.JButton();
        jActualizarClave = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jIngresar = new javax.swing.JButton();
        jTextField28 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jInventor3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(44, 109, 212));
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel9MouseDragged(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMinimizar1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bMinimizar1.setForeground(new java.awt.Color(255, 255, 255));
        bMinimizar1.setText("-");
        bMinimizar1.setBorder(null);
        bMinimizar1.setBorderPainted(false);
        bMinimizar1.setContentAreaFilled(false);
        bMinimizar1.setRolloverEnabled(false);
        bMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinimizar1ActionPerformed(evt);
            }
        });
        jPanel9.add(bMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 20, 20));

        bSalir1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bSalir1.setForeground(new java.awt.Color(255, 255, 255));
        bSalir1.setText("x");
        bSalir1.setBorder(null);
        bSalir1.setBorderPainted(false);
        bSalir1.setContentAreaFilled(false);
        bSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalir1ActionPerformed(evt);
            }
        });
        jPanel9.add(bSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 20, 20));

        bRegresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bRegresar.setForeground(new java.awt.Color(255, 255, 255));
        bRegresar.setText("<");
        bRegresar.setBorder(null);
        bRegresar.setBorderPainted(false);
        bRegresar.setContentAreaFilled(false);
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });
        jPanel9.add(bRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        lBarra.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        lBarra.setForeground(new java.awt.Color(240, 240, 240));
        lBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBarra.setText("Inventor");
        lBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lBarraMouseDragged(evt);
            }
        });
        lBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lBarraMousePressed(evt);
            }
        });
        jPanel9.add(lBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        jPanel1.setBackground(new java.awt.Color(49, 126, 247));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 890, 10));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 150, 30));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 60, 30));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Clave de empresa:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 170, 30));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 50, 30));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Datos de la dirección:");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Clave de delegación:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 30));
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 50, 30));

        jDelegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/condelegacion.png"))); // NOI18N
        jDelegacion.setToolTipText("Consultar delegación.");
        jDelegacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDelegacionMouseClicked(evt);
            }
        });
        jPanel1.add(jDelegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 50, 50));

        jColonia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/concolonia.png"))); // NOI18N
        jColonia.setToolTipText("Consultar colonia.");
        jColonia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jColoniaMouseClicked(evt);
            }
        });
        jPanel1.add(jColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 50, 50));
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, 30));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Clave de colonia:");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, 30));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Clave de calle:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 130, 30));
        jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 50, 30));

        jCalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/concalle.png"))); // NOI18N
        jCalle.setToolTipText("Consultar calle.");
        jCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalleMouseClicked(evt);
            }
        });
        jPanel1.add(jCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVergas2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 110));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Nombre:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 80, 30));
        jPanel1.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 480, 30));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Clave del inventor");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 170, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Datos del inventor:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 20));
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 50, 30));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Clave del asesor:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 160, 30));
        jPanel1.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 150, 30));

        jInventor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/coninventor.png"))); // NOI18N
        jInventor.setToolTipText("Consultar inventor asignado.");
        jInventor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInventorMouseClicked(evt);
            }
        });
        jPanel1.add(jInventor, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 50, 50));

        jEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conempresa.png"))); // NOI18N
        jEmpresa.setToolTipText("Consultar empresas.");
        jEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresaMouseClicked(evt);
            }
        });
        jPanel1.add(jEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 50, 50));

        jEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/borrar.png"))); // NOI18N
        jEliminar.setToolTipText("Borrar elemento.");
        jEliminar.setContentAreaFilled(false);
        jEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEliminarMouseClicked(evt);
            }
        });
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 50, 50));

        jActualizarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/actualizarclave.png"))); // NOI18N
        jActualizarClave.setToolTipText("Actualizar elemento.");
        jActualizarClave.setContentAreaFilled(false);
        jActualizarClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarClaveMouseClicked(evt);
            }
        });
        jActualizarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarClaveActionPerformed(evt);
            }
        });
        jPanel1.add(jActualizarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 50, 50));

        jActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/actualizar.png"))); // NOI18N
        jActualizar.setToolTipText("Seleccionar elemento a actualizar.");
        jActualizar.setContentAreaFilled(false);
        jActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarMouseClicked(evt);
            }
        });
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 50, 50));

        jIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/ingresar.png"))); // NOI18N
        jIngresar.setToolTipText("Ingresar elemento.");
        jIngresar.setContentAreaFilled(false);
        jIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIngresarMouseClicked(evt);
            }
        });
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 50, 50));
        jPanel1.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 150, 30));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("RFC:");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 50, 30));

        jInventor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/coninventor.png"))); // NOI18N
        jInventor3.setToolTipText("Consultar inventor asignado.");
        jInventor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInventor3MouseClicked(evt);
            }
        });
        jPanel1.add(jInventor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 890, 390));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Clave del inventor", "Nombre del inventor", "Clav. Deleg", "Clav. Col.", "Clav. Calle", "Clav. asesorado"
            }
        ));
        jTable4.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 830, 160));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 890, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinimizar1ActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_bMinimizar1ActionPerformed

    private void bSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalir1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_bSalir1ActionPerformed

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseDragged

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MousePressed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        new IAE_Menú().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarActionPerformed

    private void lBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lBarraMouseDragged

    private void lBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lBarraMousePressed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jActualizarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarClaveActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIngresarActionPerformed

    private void jDelegacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDelegacionMouseClicked
        // TODO add your handling code here:
        {                                         
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec DEL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("DELEGACIÓN");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { }
    }
    }//GEN-LAST:event_jDelegacionMouseClicked

    private void jEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresaMouseClicked
 {                                      
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec EMP");
    tabla.addColumn("CLAVE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("DELEGACION");
    
    while (rs.next())
    {
        Object dato[]=new Object[5];
        for (int i=0;i<5;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jEmpresaMouseClicked

    private void jColoniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColoniaMouseClicked
 {                                      
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec col");
    tabla.addColumn("CLAVE");
    tabla.addColumn("COLONIA");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jColoniaMouseClicked

    private void jCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalleMouseClicked
 {                                    
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec CAL");
    tabla.addColumn("CLAVE");
    tabla.addColumn("CALLE");
    while (rs.next())
    {
        Object dato[]=new Object[2];
        for (int i=0;i<2;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable4.setModel(tabla);
    }
    catch(Exception e) { }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jCalleMouseClicked

    private void jIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIngresarMouseClicked
 try{
                    
                    String clave_i, nom_i,rfc, fecha, col, cal, del, emp, ases;
                     
                    clave_i=jTextField25.getText();
                    nom_i=jTextField26.getText();
                    rfc=jTextField28.getText();
                    fecha=jTextField7.getText();
                    col=jTextField23.getText();
                    cal=jTextField22.getText();
                    del=jTextField24.getText();
                    emp=jTextField8.getText();
                    ases=jTextField27.getText();
                    clave_i=clave_i.toUpperCase();
                    nom_i=nom_i.toUpperCase();
                    rfc=rfc.toUpperCase();
                    fecha=fecha.toUpperCase();
                    col=col.toUpperCase();
                    cal=cal.toUpperCase();
                    del=del.toUpperCase();
                    emp=emp.toUpperCase();
                    ases=ases.toUpperCase();
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                    ResultSet rs=stmt.executeQuery("exec i_invent1 '"+clave_i+"','"+nom_i+"','"+rfc+"','"+fecha+"','"+col+"','"+cal+"','"+del+"','"+emp+"','"+ases+"'");
                    
                }
                catch(SQLException e)  {
                    
                }    jTextField25.setText("");jTextField26.setText("");jTextField28.setText("");jTextField7.setText("");jTextField23.setText("");
                jTextField22.setText("");jTextField24.setText("");jTextField8.setText("");jTextField27.setText(""); jTextField25.setEnabled(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jIngresarMouseClicked

    private void jInventorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInventorMouseClicked
        {
            // TODO add your handling code here:
            try
            {

                DefaultTableModel tabla=new DefaultTableModel();
                Connection con;
                con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery("exec INV");
                tabla.addColumn("CLAVE");
                tabla.addColumn("INVENTOR");
                tabla.addColumn("RFC");
                tabla.addColumn("FECHA");
                tabla.addColumn("DELEGACIÓN");
                tabla.addColumn("COLONIA");
                tabla.addColumn("CALLE");
                tabla.addColumn("EMPRESA");
                tabla.addColumn("ASESOR");
                while (rs.next())
                {
                    Object dato[]=new Object[9];
                    for (int i=0;i<9;i++)
                    {
                        dato[i]=rs.getString(i+1);
                    }
                    tabla.addRow(dato);
                }
                this.jTable4.setModel(tabla);
            }
            catch(Exception e) { }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jInventorMouseClicked

    private void jInventor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInventor3MouseClicked
        {
            // TODO add your handling code here:
            try
            {

                DefaultTableModel tabla=new DefaultTableModel();
                Connection con;
                con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery("exec INV");
                tabla.addColumn("CLAVE");
                tabla.addColumn("INVENTOR");
                tabla.addColumn("RFC");
                tabla.addColumn("FECHA");
                tabla.addColumn("DELEGACIÓN");
                tabla.addColumn("COLONIA");
                tabla.addColumn("CALLE");
                tabla.addColumn("EMPRESA");
                tabla.addColumn("ASESOR");
                while (rs.next())
                {
                    Object dato[]=new Object[9];
                    for (int i=0;i<9;i++)
                    {
                        dato[i]=rs.getString(i+1);
                    }
                    tabla.addRow(dato);
                }
                this.jTable4.setModel(tabla);
            }
            catch(Exception e) { }
        }       // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jInventor3MouseClicked

    private void jEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEliminarMouseClicked
 try{      
            String clave_t;
             clave_t = jTextField25.getText();
                
         
                  Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                 ResultSet rs=stmt.executeQuery("exec bor6 "+clave_t+"");
        }
        catch(Exception e) { JOptionPane.showMessageDialog(null, e);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jEliminarMouseClicked

    private void jActualizarClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarClaveMouseClicked
 try{
                    
                    String clave_i, nom_i,rfc, fecha, col, cal, del, emp, ases;
                     
                    clave_i=jTextField25.getText();
                    nom_i=jTextField26.getText();
                    rfc=jTextField28.getText();
                    fecha=jTextField7.getText();
                    col=jTextField23.getText();
                    cal=jTextField22.getText();
                    del=jTextField24.getText();
                    emp=jTextField8.getText();
                    ases=jTextField27.getText();
                    clave_i=clave_i.toUpperCase();
                    nom_i=nom_i.toUpperCase();
                    rfc=rfc.toUpperCase();
                    fecha=fecha.toUpperCase();
                    col=col.toUpperCase();
                    cal=cal.toUpperCase();
                    del=del.toUpperCase();
                    emp=emp.toUpperCase();
                    ases=ases.toUpperCase();
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                    ResultSet rs=stmt.executeQuery("exec act6 '"+clave_i+"','"+nom_i+"','"+rfc+"','"+fecha+"','"+col+"','"+cal+"','"+del+"','"+emp+"','"+ases+"'");
                    
                }
                catch(SQLException e)  {
                    
                }    jTextField25.setEnabled(true);jTextField25.setText("");jTextField26.setText("");jTextField28.setText("");jTextField7.setText("");jTextField23.setText("");
                jTextField22.setText("");jTextField24.setText("");jTextField8.setText("");jTextField27.setText("");   // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarClaveMouseClicked

    private void jActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarMouseClicked
try{      
            String clave_c;
             clave_c = jTextField25.getText();
                
         
                  Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                 ResultSet rs=stmt.executeQuery("select *from inventor where clave_inv='"+clave_c+"'");
                if (rs.next()) {
                    jTextField25.setText(String.valueOf(rs.getString(1)));
                    jTextField26.setText(String.valueOf(rs.getString(2)));
                    jTextField28.setText(String.valueOf(rs.getString(3)));
                    jTextField7.setText(String.valueOf(rs.getString(4)));
                    jTextField24.setText(String.valueOf(rs.getString(5)));
                    jTextField23.setText(String.valueOf(rs.getString(6)));
                    jTextField22.setText(String.valueOf(rs.getString(7)));
                    jTextField8.setText(String.valueOf(rs.getString(8)));
                    jTextField27.setText(String.valueOf(rs.getString(9)));
                                         
                    jTextField25.setEnabled(false);
                    
                     
                    stmt.close();
                    
                } 
            } 
        catch (SQLException e) {
         //   JOptionPane.showMessageDialog(null, e);
                
            }       // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IAE_Inventor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IAE_Inventor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IAE_Inventor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IAE_Inventor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IAE_Inventor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMinimizar1;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bSalir1;
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jActualizarClave;
    private javax.swing.JLabel jCalle;
    private javax.swing.JLabel jColonia;
    private javax.swing.JLabel jDelegacion;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jEmpresa;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jInventor;
    private javax.swing.JLabel jInventor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lBarra;
    // End of variables declaration//GEN-END:variables
}
