/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IngresarActualizarEliminar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class IAE_Patentes extends javax.swing.JFrame {

    /**
     * Creates new form I_Patentes
     */
    public IAE_Patentes() {
        initComponents();
    }
    int x,y;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPatente = new javax.swing.JLabel();
        jInventor = new javax.swing.JLabel();
        jEliminar = new javax.swing.JButton();
        jActualizarClave = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jIngresar = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jEmpresa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bSalir = new javax.swing.JButton();
        bMinimizar = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();
        lBarra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(49, 126, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 80, 30));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 140, 30));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clave de la patente:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 160, 30));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre del Invento:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, 30));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 110, 30));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVergas2.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 150));

        jPatente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conpatente.png"))); // NOI18N
        jPatente.setToolTipText("Consultar patente.");
        jPatente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatenteMouseClicked(evt);
            }
        });
        jPanel2.add(jPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, 50));

        jInventor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/coninventor.png"))); // NOI18N
        jInventor.setToolTipText("Consultar Inventor");
        jInventor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInventorMouseClicked(evt);
            }
        });
        jPanel2.add(jInventor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 50, 50));

        jEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/borrar.png"))); // NOI18N
        jEliminar.setToolTipText("Borrar elemento.");
        jEliminar.setContentAreaFilled(false);
        jEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEliminarMouseClicked(evt);
            }
        });
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 50, 50));

        jActualizarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/actualizarclave.png"))); // NOI18N
        jActualizarClave.setToolTipText("Actualizar elemento.");
        jActualizarClave.setContentAreaFilled(false);
        jActualizarClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarClaveMouseClicked(evt);
            }
        });
        jActualizarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarClaveActionPerformed(evt);
            }
        });
        jPanel2.add(jActualizarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 50, 50));

        jActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/actualizar.png"))); // NOI18N
        jActualizar.setToolTipText("Seleccionar elemento a actualizar.");
        jActualizar.setContentAreaFilled(false);
        jActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActualizarMouseClicked(evt);
            }
        });
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 50, 50));

        jIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/ingresar.png"))); // NOI18N
        jIngresar.setToolTipText("Ingresar elemento.");
        jIngresar.setContentAreaFilled(false);
        jIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIngresarMouseClicked(evt);
            }
        });
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(jIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 50, 50));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, 30));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clave del inventor:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        jEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/conempresa.png"))); // NOI18N
        jEmpresa.setToolTipText("Consultar empresas.");
        jEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEmpresaMouseClicked(evt);
            }
        });
        jPanel2.add(jEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 50, 50));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Clave de la empresa:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, 30));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 260));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Clave de la patente", "Nombre de la patente", "Clave del inventor"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 720, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 780, 300));

        jPanel4.setBackground(new java.awt.Color(44, 109, 212));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("x");
        bSalir.setBorder(null);
        bSalir.setBorderPainted(false);
        bSalir.setContentAreaFilled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel4.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 20, 20));

        bMinimizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        bMinimizar.setText("-");
        bMinimizar.setBorder(null);
        bMinimizar.setBorderPainted(false);
        bMinimizar.setContentAreaFilled(false);
        bMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinimizarActionPerformed(evt);
            }
        });
        jPanel4.add(bMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 20, 20));

        bRegresar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        bRegresar.setForeground(new java.awt.Color(255, 255, 255));
        bRegresar.setText("<");
        bRegresar.setBorder(null);
        bRegresar.setBorderPainted(false);
        bRegresar.setContentAreaFilled(false);
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });
        jPanel4.add(bRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        lBarra.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        lBarra.setForeground(new java.awt.Color(240, 240, 240));
        lBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBarra.setText("Patente");
        lBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lBarraMouseDragged(evt);
            }
        });
        lBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lBarraMousePressed(evt);
            }
        });
        jPanel4.add(lBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_bMinimizarActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        new IAE_Menú().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRegresarActionPerformed

    private void lBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lBarraMouseDragged

    private void lBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lBarraMousePressed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jActualizarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarClaveActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIngresarActionPerformed

    private void jEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmpresaMouseClicked
        {                                      
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec EMP");
    tabla.addColumn("CLAVE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("DELEGACION");
    
    while (rs.next())
    {
        Object dato[]=new Object[5];
        for (int i=0;i<5;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable2.setModel(tabla);
    }
    catch(Exception e) { }
    }// TODO add your handling code here:
    }//GEN-LAST:event_jEmpresaMouseClicked

    private void jInventorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInventorMouseClicked
 {                                       
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec INV");
    tabla.addColumn("CLAVE");
    tabla.addColumn("INVENTOR");
    tabla.addColumn("RFC");
    tabla.addColumn("FECHA");
    tabla.addColumn("DELEGACIÓN");
    tabla.addColumn("COLONIA");
    tabla.addColumn("CALLE");
    tabla.addColumn("EMPRESA");
    tabla.addColumn("ASESOR");
    while (rs.next())
    {
        Object dato[]=new Object[9];
        for (int i=0;i<9;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable2.setModel(tabla);
    }
    catch(Exception e) { }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jInventorMouseClicked

    private void jPatenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatenteMouseClicked
{                                      
        // TODO add your handling code here:
        try
    {
        
    DefaultTableModel tabla=new DefaultTableModel();
     Connection con;
     con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES; user=sa; password=sasa;");
    Statement stmt=con.createStatement();
    ResultSet rs=stmt.executeQuery("exec Pat");
    tabla.addColumn("CLAVE");
    tabla.addColumn("PATENTE");
    tabla.addColumn("FECHA");
    tabla.addColumn("INVENTOR");
    tabla.addColumn("EMPRESA");
    
    while (rs.next())
    {
        Object dato[]=new Object[5];
        for (int i=0;i<5;i++)
        {
            dato[i]=rs.getString(i+1);
        }
        tabla.addRow(dato);
    }
    this.jTable2.setModel(tabla);
    }
    catch(Exception e) { 
    //    JOptionPane.showMessageDialog(null,e);
    }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jPatenteMouseClicked

    private void jIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIngresarMouseClicked
        // TODO add your handling code here:try{
                try{    
                    String clave_p, nom_p, fecha, emp, ases;
                     
                    clave_p=jTextField1.getText();
                    nom_p=jTextField2.getText();
                  
                    fecha=jTextField3.getText();
                    
                    emp=jTextField5.getText();
                    ases=jTextField4.getText();
                    clave_p=clave_p.toUpperCase();
                    nom_p=nom_p.toUpperCase();
                    fecha=fecha.toUpperCase();
                    emp=emp.toUpperCase();
                    ases=ases.toUpperCase();
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                    ResultSet rs=stmt.executeQuery("exec i_patent1 '"+clave_p+"','"+nom_p+"','"+fecha+"','"+ases+"','"+emp+"'");
                    
                }
                catch(SQLException e)  {
                    //JOptionPane.showMessageDialog(null,e);
                } 
                jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");jTextField4.setText("");jTextField5.setText(""); jTextField1.setEnabled(true);
    }//GEN-LAST:event_jIngresarMouseClicked

    private void jActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarMouseClicked
        // TODO add your handling code here:
        try{      
            String clave_c;
             clave_c = jTextField1.getText();
                
         
                  Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PATENTES;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                 ResultSet rs=stmt.executeQuery("select *from PATENTE where clave_PAN='"+clave_c+"'");
                if (rs.next()) {
                    jTextField1.setText(String.valueOf(rs.getString(1)));
                    jTextField3.setText(String.valueOf(rs.getString(3)));
                    jTextField2.setText(String.valueOf(rs.getString(2)));
                    jTextField4.setText(String.valueOf(rs.getString(4)));
                    jTextField5.setText(String.valueOf(rs.getString(5)));
                    
                                         
                    jTextField1.setEnabled(false);
                    
                     
                    stmt.close();
                    
                } 
            } 
        catch (SQLException e) {
            //JOptionPane.showMessageDialog(null, e);
                
            }
    }//GEN-LAST:event_jActualizarMouseClicked

    private void jActualizarClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActualizarClaveMouseClicked
        // TODO add your handling code here:
         try{    
                    String clave_p, nom_p, fecha, emp, ases;
                     
                    clave_p=jTextField1.getText();
                    nom_p=jTextField2.getText();
                  
                    fecha=jTextField3.getText();
                    
                    emp=jTextField5.getText();
                    ases=jTextField4.getText();
                    clave_p=clave_p.toUpperCase();
                    nom_p=nom_p.toUpperCase();
                    fecha=fecha.toUpperCase();
                    emp=emp.toUpperCase();
                    ases=ases.toUpperCase();
                    Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                    ResultSet rs=stmt.executeQuery("exec act7 '"+clave_p+"','"+nom_p+"','"+fecha+"','"+ases+"','"+emp+"'");
                    
                }
                catch(SQLException e)  {
//JOptionPane.showMessageDialog(null,e);                    
                } 
                jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");jTextField4.setText("");jTextField5.setText(""); jTextField1.setEnabled(true);
    }//GEN-LAST:event_jActualizarClaveMouseClicked

    private void jEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEliminarMouseClicked
  try{      
            String clave_t;
             clave_t = jTextField1.getText();
                
         
                  Connection con;
                    con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=patentes;user=sa;password=sasa;");
                    Statement stmt= con.createStatement();
                 ResultSet rs=stmt.executeQuery("exec bor7 "+clave_t+"");
        }
        catch(Exception e) {// JOptionPane.showMessageDialog(null, e);
        } jTextField1.setText("");       // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_jEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IAE_Patentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IAE_Patentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IAE_Patentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IAE_Patentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IAE_Patentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMinimizar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jActualizarClave;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jEmpresa;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jInventor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPatente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lBarra;
    // End of variables declaration//GEN-END:variables
}
